#!/bin/sh
### BEGIN INIT INFO
# Provides:          inetbox2mqtt
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start inetbox2mqtt on boot
# Description:       Starts the Python script to run MQTT integration
### END INIT INFO

SCRIPT_PATH="/opt/inetbox2mqtt/src/main.py"
PIDFILE="/var/run/inetbox2mqtt.pid"
LOGFILE="/var/log/inetbox2mqtt.log"
USER="root"  # Or another user if appropriate

start() {
    echo "Starting inetbox2mqtt..."
    if [ -f $PIDFILE ]; then
        echo "Already running (PID $(cat $PIDFILE))"
        return 1
    fi
    nohup python3 $SCRIPT_PATH >> $LOGFILE 2>&1 &
    echo $! > $PIDFILE
    echo "Started with PID $(cat $PIDFILE)"
}

stop() {
    echo "Stopping inetbox2mqtt..."
    if [ -f $PIDFILE ]; then
        kill $(cat $PIDFILE)
        rm -f $PIDFILE
        echo "Stopped."
    else
        echo "Not running."
    fi
}

status() {
    if [ -f $PIDFILE ]; then
        echo "inetbox2mqtt is running (PID $(cat $PIDFILE))"
    else
        echo "inetbox2mqtt is not running."
    fi
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) stop && start ;;
    status) status ;;
    *) echo "Usage: $0 {start|stop|restart|status}" ;;
esac

exit 0
